version: "3"

services:
  database:
    container_name: wallet_db
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    command: mongod
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  app:
    container_name: wallet_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: npm run dev
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - database
    environment:
      NODE_ENV: ${NODE_ENV}
