version: "3"

services:
  database:
    build: ./docker/database
    command: mongod --port 27027
    image: mongo
    restart: always
    ports:
      - 27027:27027
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  app:
    # build: .
    build: ./docker/app
    command: npm run dev 
    ports:
      - 3002:3002
    volumes:
      - .:/usr/app
    restart: always
    depends_on:
      - database
    environment:
      NODE_ENV: ${NODE_ENV}
